### ISSUE TITLE
Bevy 0.2 compatibility

### ISSUE THREAD

**Issue by ffactory-ofcl** [PradeepKumarRajamanickam/bevy_input_map#12]
I'm getting this error:
```
the trait bevy::prelude::Plugin is not implemented for bevy_prototype_input_map::InputMapPlugin
```

Could this be because you have bevy 0.1 in your Cargo.toml, i.e. a version mismatch?

**Comment by ndarilek** [comment]
Yeah, I believe that's the issue.

I spent a few minutes looking at this. Seems like the serde derives were omitted from the gamepad types in Bevy. I copied them from keyboard.rs and submitted https://github.com/bevyengine/bevy/pull/583 which seems to eliminate the compilation errors in bevy_input_map.

As an aside, it's hard to spot compiler errors amid the warning spam. I'll take a crack at fixing those if no one else gets to it.

**Comment by PradeepKumarRajamanickam** [comment]
@ndarilek Is right bevy Gamepad does not support serde at the moment which is required for JSON/RON Binding support. There is an on going PR for this [#524](https://github.com/bevyengine/bevy/pull/524). But I am not getting enough time to finish this PR at the moment.

**Comment by PradeepKumarRajamanickam** [comment]
Actually @ndarilek PR might be enough at the moment since I have create custom serde util methods which works around the need to serialise struct tuples. I have posted a comment on  bevyengine/bevy#583, tagging Carter lets see how he wants to proceed.

**Comment by PradeepKumarRajamanickam** [comment]
Closing issue. As of v0.1.4, bevy 0.2 is supported. I have added release tags to identify stable checkouts. Master is where active development happens, I expect it to break often. Tags will allow visitors to identify stable commits.
