### ISSUE TITLE
Support mapping to arbitrary types 

### ISSUE THREAD

**Issue by Plecra** [PradeepKumarRajamanickam/bevy_input_map#34]
```rust
enum Input {
    Jump,
    Shoot,
}
input_map
    .bind_keyboard_pressed(KeyCode::Space, Input::Jump)
    .bind_keyboard_pressed(KeyCode::Return, Input::Shoot)

if input_map.is_action_active(Input::Jump) {
    // Jump
}
```

This would help avoid typos (in JSON too - `Deserialize` can check for valid inputs), allow the inputs to be directly documented, and make function signatures clearer (`fn(Input)` instead of `fn(&str)`).

It shouldn't have any real overhead internally - `String` and `Box<dyn Any>` have effectively the same representation, and need the same number of checks (deref -> length -> equality for `String` and TypeId -> deref -> equality for `Box<dyn Any>`)

**Comment by PradeepKumarRajamanickam** [comment]
Input map's main design goal is to be data driven and editor centric. Using strings is ideal as it simplifies things. Supporting arbitrary types will add additional complexity which I want to avoid. 

Closing ticket.
